#
# Inject Linkerd Proxy to this
#
podAnnotations:
  linkerd.io/inject: enabled

#
# OC collector configuration
#
config: |
  receivers:
    opencensus:
      port: 55678
    zipkin:
      port: 9411
  queued-exporters:
    jaeger-all-in-one:
      num-workers: 4
      queue-size: 100
      retry-on-failure: true
      sender-type: jaeger-thrift-http
      jaeger-thrift-http:
        collector-endpoint: http://jaeger.tracing:14268/api/traces
        timeout: 5s
