apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: {{ include "cert-manager-issuer.fullname" . }}
  labels:
    app: {{ template "cert-manager-issuer.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  acme:
    server: {{ .Values.clusterissuer.acme.server }}
    email: {{ .Values.clusterissuer.acme.email }}
    privateKeySecretRef:
      name: {{ include "cert-manager-issuer.fullname" . }}
    dns01:
      providers:
      - name: route53
        route53:
          region: {{ .Values.clusterissuer.route53.region }}
          {{ if .Values.clusterissuer.route53.hostedZoneID -}}
          hostedZoneID: {{ .Values.clusterissuer.route53.hostedZoneID }}
          {{ end -}}
          accessKeyID: {{ .Values.clusterissuer.route53.accessKeyID }}
          secretAccessKeySecretRef:
            name: {{ include "cert-manager-issuer.fullname" . }}-secret-access-key
            key: secret-access-key
