apiVersion: apps/v1
kind: Deployment
metadata:
{{- if .Values.ingressMonitorController.useFullName }}
  name: {{ template "ingressmonitorcontroller.fullname" . }}
{{- else }}
  name: {{ template "ingressmonitorcontroller.name" . }}
{{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "ingressmonitorcontroller.name" . }}
      release: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app: {{ template "ingressmonitorcontroller.name" . }}
        release: {{ .Release.Name | quote }}
    spec:
      {{- if .Values.ingressMonitorController.useFullName }}
      serviceAccountName: {{ template "ingressmonitorcontroller.fullname" . }}
      {{- else }}
      serviceAccountName: {{ template "ingressmonitorcontroller.name" . }}
      {{- end }}
      containers:
        - name: ingressmonitorcontroller
          image: "{{ .Values.ingressMonitorController.image.name }}:{{ .Values.ingressMonitorController.image.tag }}"
          command:
            - IngressMonitorController
          imagePullPolicy: Always
          imagePullPolicy: {{ .Values.ingressMonitorController.image.pullPolicy }}
          env:
            - name: WATCH_NAMESPACE
              value: {{ .Values.ingressMonitorController.watchNamespace | quote }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ingressmonitorcontroller"
            - name: CONFIG_SECRET_NAME
              value: {{ .Values.ingressMonitorController.configSecretName | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.ingressMonitorController.logLevel }}
            - name: LOG_FORMAT
              value: {{ .Values.ingressMonitorController.logFormat }}
