apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.ingressMonitorController.configSecretName | quote }}
data:
{{- range $key, $value := .Values.ingressMonitorController.data }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
