#
# Image Attributes
#
image:
  repository: fluent/fluentd-kubernetes-daemonset
  tag: v1.2-debian-elasticsearch
  pullPolicy: IfNotPresent

#
# ServiceAccount (ClusterRole and ClusterRoleBinding)
#
serviceAccount:
  create: true
  name: ""

#
# RBAC Permissions
#
rbac:
  create: true

#
# Environment Variables
#
env: {}
  # FLUENT_ELASTICSEARCH_HOST: "elasticsearch.domain.com"
  # FLUENT_ELASTICSEARCH_PORT: "9200"
  # FLUENT_ELASTICSEARCH_SCHEME: "http"
  # FLUENT_UID: "0"
  # FLUENT_ELASTICSEARCH_LOGSTASH_PREFIX: "fluentd-apps"
  # FLUENT_ELASTICSEARCH_USER: none
  # FLUENT_ELASTICSEARCH_PASSWORD: none

#
# ConfigMaps is a dictionary that define filenames and their contents. These
# will be mounted to the FluentD configuration path
#
configMaps: {}
  # fluent.conf: |
  #   @include systemd.conf
  #   @include kubernetes.conf
  # 
  #   <match **>
  #     @type elasticsearch
  #     @id out_es
  #     log_level info
  #     include_tag_key true
  #     host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
  #     port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
  #     scheme "#{ENV['FLUENT_ELASTICSEARCH_SCHEME'] || 'http'}"
  #     ssl_verify "#{ENV['FLUENT_ELASTICSEARCH_SSL_VERIFY'] || 'true'}"
  #     reload_connections "#{ENV['FLUENT_ELASTICSEARCH_RELOAD_CONNECTIONS'] || 'true'}"
  #     logstash_prefix "#{ENV['FLUENT_ELASTICSEARCH_LOGSTASH_PREFIX'] || 'fluentd-apps'}"
  #     logstash_format true
  #     buffer_chunk_limit 2M
  #     buffer_queue_limit 32
  #     flush_interval 5s
  #     max_retry_wait 30
  #     disable_retry_limit
  #     num_threads 8
  #   </match>
  # 
  # kubernetes.conf: |
  #   <match fluent.**>
  #     @type null
  #   </match>
  # 
  #   <match kubernetes.var.log.containers.**kube-apiserver**.log>
  #    @type null
  #   </match>
  # 
  #   <match kubernetes.var.log.containers.**kube-state-metrics**.log>
  #    @type null
  #   </match>
  # 
  #   <match kubernetes.var.log.containers.**kube-public**.log>
  #    @type null
  #   </match>
  # 
  #   <match kubernetes.var.log.containers.**default**.log>
  #    @type null
  #   </match>
  # 
  #   <source>
  #     @type tail
  #     @id in_tail_container_logs
  #     path /var/log/containers/*.log
  #     pos_file /var/log/fluentd-containers.log.pos
  #     tag kubernetes.*
  #     read_from_head true
  #     <parse>
  #       @type json
  #       json_parser json
  #       time_format %Y-%m-%dT%H:%M:%S.%NZ
  #     </parse>
  #   </source>
  # 
  #   <source>
  #     @type tail
  #     @id in_tail_docker
  #     path /var/log/docker.log
  #     pos_file /var/log/fluentd-docker.log.pos
  #     tag docker
  #     <parse>
  #       @type regexp
  #       expression /^time="(?<time>[^)]*)" level=(?<severity>[^ ]*) msg="(?<message>[^"]*)"( err="(?<error>[^"]*)")?( statusCode=($<status_code>\d+))?/
  #     </parse>
  #   </source>
  # 
  #   <filter kubernetes.**>
  #     @type kubernetes_metadata
  #     @id filter_kube_metadata
  #   </filter>
  # 
  #   <filter kubernetes.var.log.containers.**>
  #     @type parser
  #     <parse>
  #       @type json
  #       json_parser json
  #     </parse>
  #     replace_invalid_sequence true
  #     emit_invalid_record_to_error false
  #     key_name log
  #     reserve_data true
  #   </filter>

#
# Pod Resource Requests and Limits
#
resources: {}
  # limits:
  #  cpu: 500m
  #  memory: 200Mi
  # requests:
  #  cpu: 500m
  #  memory: 200Mi

#
# Node Selectors
#
nodeSelector: {}

#
# Tolerations
#
tolerations: []

#
# Pod Affinity
#
affinity: {}
