apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drone-tree-config.fullname" . }}
  labels:
    {{- include "drone-tree-config.labels" . | nindent 4 }}
type: Opaque
data:
  GITHUB_TOKEN: {{ .Values.config.GITHUB_TOKEN | toString | b64enc | quote }}
  PLUGIN_SECRET: {{ .Values.config.PLUGIN_SECRET | toString | b64enc | quote }}
