version: 2

jobs:
  chagelog-patch:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true

    steps:
      - checkout

      - run: pwd

      - run: ls -ltra

      - run:
          name: git-chglog generation for path release
          command: make changelog-patch

workflows:
  version: 2
  changelog_and_release:
    jobs:
      - chagelog-patch