version: 2

jobs:
  chagelog-patch:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true

    steps:
      - checkout

      - run: pwd

      - run: ls -ltra

      - run:
          name: make changelog-patch && git add && git commit && make release-patch
          command: make release-patch-with-changelog

workflows:
  version: 2
  changelog_and_release:
    jobs:
      - chagelog-patch