version: 2

jobs:
  release-patch-with-changelog:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "2d:9c:2e:a5:a4:77:0b:a7:91:2c:f1:14:1c:3a:65:e1"

      - run: pwd

      - run: ls -ltra

      - run:
          name: release-patch-with-changelog-circleci
          command: |
            if git status | grep 'nothing to commit, working tree clean'; then
              echo "==============================================================================================="
              echo "release-patch-with-changelog-circleci"
              echo "==============================================================================================="
              make release-patch-with-changelog-circleci
            else
              echo "==============================================================================================="
              echo "Changes in working directory pending to be pushed - please check 'git status' cmd output below "
              echo "==============================================================================================="
              echo "$(git status)"
              echo "==============================================================================================="
            fi

      - run:
          name: make changelog-patch && git add && git commit && make release-patch
          command: make release-patch-with-changelog

workflows:
  version: 2
  changelog_and_release:
    jobs:
      - release-patch-with-changelog