apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "kube-job-cleaner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "kube-job-cleaner.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  schedule: "{{ .Values.cronJob.schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ template "kube-job-cleaner.name" . }}
            chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
            release: "{{ .Release.Name }}"
            heritage: "{{ .Release.Service }}"
        spec:
          serviceAccountName: kube-job-cleaner
          restartPolicy: OnFailure
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.cronJob.image.repository }}:{{ .Values.cronJob.image.tag }}"
            imagePullPolicy: {{ .Values.cronJob.image.pullPolicy }}
            resources:
              {{- toYaml .Values.resources | nindent 24 }}
