{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "kube-job-cleaner.fullname" . }}
  labels:
    app: {{ template "kube-job-cleaner.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: {{ template "kube-job-cleaner.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
