apiVersion: cert-manager.io/v1beta1
kind: ClusterIssuer
metadata:
  name: {{ include "cert-manager-clusterissuer.fullname" . }}
  labels:
    app: {{ template "cert-manager-clusterissuer.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  acme:
    server: {{ .Values.clusterissuer.acme.server }}
    email: {{ .Values.clusterissuer.acme.email }}
    privateKeySecretRef:
      name: {{ include "cert-manager-clusterissuer.fullname" . }}
    solvers:
      - selector:
          dnsZones: {{ .Values.clusterissuer.selector.dnsZones }}
        dns01:
          route53:
            region: {{ .Values.clusterissuer.route53.region }}
            {{ if .Values.clusterissuer.route53.hostedZoneID -}}
            hostedZoneID: {{ .Values.clusterissuer.route53.hostedZoneID }}
            {{ end -}}
            accessKeyID: {{ .Values.clusterissuer.route53.accessKeyID }}
            secretAccessKeySecretRef:
              name: {{ include "cert-manager-clusterissuer.fullname" . }}-secret-access-key
              key: secret-access-key
