apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "onetimesecret.fullname" . }}-ots-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "onetimesecret.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  config: |-
    :site:
      :host: {{ .Values.app.site.host }}
      :domain: {{ .Values.app.site.domain }}
      :ssl: {{ .Values.app.site.ssl }}
      # NOTE Once the secret is set, do not change it (keep a backup offsite)
      :secret: {{ .Values.app.site.secret }}
    :redis:
      :uri: {{ .Values.app.redis.uri }}
      :config: {{ .Values.app.redis.config }}
    :colonels:
      # Accounts created with the following email addresses
      # are automatically considered admins of the system.
      {{- toYaml .Values.app.colonels | nindent 6 }}
    :emailer:
      :mode: :sendgrid
      :account: CHANGEME
      :password: CHANGEME
      :from: CHANGEME@example.com
      :fromname: CHANGEME
      :bcc:
    :incoming:
      # Intended for use by IT support teams who need someone to send them
      # sensitive info. The email address is where the secret
      # link is sent. Passphrase is used to protect the secret.
      # The regex used to ensure the ticket number is valid.
      # See: https://onetimesecret.com/incoming
      :enabled: false
      :email: incoming@binbash.com.ar
      :passphrase: CHANGEME
      :regex: \A[a-zA-Z0-9]{6}\z
    :locales:
      - en
      - es
      - ru
    :unsupported_locales:
      - pt
      - jp
      - cn
      - it
    :stathat:
      :enabled: false
      :apikey: CHANGEME
      :default_chart: CHANGEME
    :text:
      :nonpaid_recipient_text: 'You need to create an account!'
      :paid_recipient_text: 'Send the secret link via email'
    :limits:
      :create_secret: 250
      :create_account: 0
      :update_account: 0
      :email_recipient: 0
      :send_feedback: 0
      :authenticate_session: 5
      :homepage: 500
      :dashboard: 1000
      :failed_passphrase: 5
      :show_metadata: 1000
      :show_secret: 1000
      :burn_secret: 1000
