# Default values for kube-job-cleaner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Use the following to configure when the cleaner runs and which image/version is used
cronJob:
  schedule: "0 * * * *"
  image:
    repository: hjacobs/kube-job-cleaner
    tag: 0.8
    pullPolicy: IfNotPresent

# RBAC settings
rbac:
  # If true, create & use RBAC resources
  create: true

# Service account settings
serviceAccount:
  # Specifies whether a ServiceAccount should be created, require rbac true
  create: true

# Resource names overrides (optional)
nameOverride: ""
fullnameOverride: ""

# Resources as defined in the original repository (https://github.com/hjacobs/kube-job-cleaner/blob/master/deploy/cronjob.yaml)
resources:
  limits:
    cpu: 200m
    memory: 100Mi
  requests:
    cpu: 50m
    memory: 50Mi
