kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: authorizationpolicies.security.istio.io
  labels:
    app: istio-pilot
    istio: security
    heritage: Tiller
    release: istio
spec:
  group: security.istio.io
  names:
    kind: AuthorizationPolicy
    plural: authorizationpolicies
    singular: authorizationpolicy
    categories:
      - istio-io
      - security-istio-io
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
---
