---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oc-collector-conf
  namespace: {{ .Release.Namespace }}
  labels:
    app: opencensus
    component: oc-collector-conf
data:
  oc-collector-config: |
{{ .Values.config | indent 4 }}
