---
apiVersion: v1
kind: Service
metadata:
  name: oc-collector
  namespace: {{ .Release.Namespace }}
  labels:
    app: opencensus
    component: oc-collector
spec:
  ports:
  - name: opencensus
    port: 55678
    protocol: TCP
    targetPort: 55678
  - name: zipkin
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    component: oc-collector