# Default values for kube-job-cleaner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# App configuration: customize these values according to your needs
app:
  site:
    host: onetimesecret.localhost
    domain: onetimesecret.localhost
    ssl: false
    secret: UseYourOwnSecretHere
  redis:
    uri: redis://127.0.0.1:7179/0?timeout=10&thread_safe=false&logging=false
    config: /etc/onetime/redis.conf
  colonels:
    - admin@localhost

# Pod configuration
pod:
  replicas: 1
  image:
    repository: binbash/onetimesecret
    tag: latest
    pullPolicy: Always

# Service configuration
service:
  podPort: 7143
  servicePort: 9090

# Ingress configuration
ingress:
  host: onetimesecret.aws.binbash.com.ar
  # Custom Skipper Ingress settings
  skipper:
    ingressClass: skipper
    loadBalancerScheme: internal

# Resource names overrides (optional)
nameOverride: ""
fullnameOverride: ""

# Node selector settings
nodeSelector:
  kops.k8s.io/instancegroup: nodes

# Resources as defined in the original repository (https://github.com/hjacobs/kube-job-cleaner/blob/master/deploy/cronjob.yaml)
resources:
  limits:
    cpu: 150m
    memory: 120Mi
  requests:
    cpu: 100m
    memory: 90Mi
