---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: jaeger
  namespace: {{ .Release.Namespace }}
  labels:
    app: jaeger
spec:
  replicas: 1
  template:
    metadata:
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
      labels:
        app: jaeger
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: jaeger
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - name: collection
          containerPort: 14268
        - name: ui
          containerPort: 16686
        resources:
{{ toYaml .Values.resources | indent 10 }}
