---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: {{ .Release.Namespace }}
  labels:
    app: jaeger
spec:
  selector:
    app: jaeger
  ports:
  - name: collection
    port: 14268
  - name: ui
    port: 16686