#
# NOTE: at the moment only ClusterIssuer is supported
#
clusterissuer:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: your.email@example.com

  selector:
    dnsZones:
      - example.com

  #
  # NOTE: at the moment only route53 is supported
  #
  route53:
    region: YOUR-AWS-REGION
    hostedZoneID: false
    accessKeyID: YOUR-ACCESS-KEY-ID
    secretAccessKeySecret: YOUR-ACCESS-KEY-SECRET
