kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ingressmonitorcontroller
subjects:
- kind: ServiceAccount
  name: ingressmonitorcontroller
  namespace: default
roleRef:
  kind: ClusterRole
  name: ingressmonitorcontroller
  apiGroup: rbac.authorization.k8s.io
