{{- if and ( .Values.ingressMonitorController.rbac.create ) (eq .Values.ingressMonitorController.watchNamespace "") }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  {{- if .Values.ingressMonitorController.useFullName }}
  name: {{ template "ingressmonitorcontroller.fullname" . }}-role-binding
  {{- else }}
  name: {{ template "ingressmonitorcontroller.name" . }}-role-binding
  {{- end }}
roleRef:
  kind: ClusterRole
  {{- if .Values.ingressMonitorController.useFullName }}
  name: {{ template "ingressmonitorcontroller.fullname" . }}-role
  {{- else }}
  name: {{ template "ingressmonitorcontroller.name" . }}-role
  {{- end }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  {{- if .Values.ingressMonitorController.useFullName }}
  name: {{ template "ingressmonitorcontroller.fullname" . }}
  {{- else }}
  name: {{ template "ingressmonitorcontroller.name" . }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
{{- end }}
