apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "ingressmonitorcontroller.name" . }}
data:
{{- range $key, $value := .Values.ingressMonitorController.data }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
