{{- if .Values.ingressMonitorController.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.ingressMonitorController.useFullName }}
  name: {{ template "ingressmonitorcontroller.fullname" . }}
  {{- else }}
  name: {{ template "ingressmonitorcontroller.name" . }}
  {{- end }}
{{- end }}
