apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "cert-manager-issuer.fullname" . }}-secret-access-key
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "cert-manager-issuer.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  secret-access-key: {{ .Values.clusterissuer.route53.secretAccessKeySecret | b64enc }}
